### ISSUE TITLE
Include PodSecurityPolicy (if required)

### ISSUE THREAD

**Issue by ScheererJ** [gardener/network-problem-detector#1]
**What happened**:
I tried to deploy the network problem detector via command line. Unfortunately, the daemon set pods could not be created due to the missing `PodSecurityPolicy`:

```
  Warning  FailedCreate  26s (x15 over 108s)  daemonset-controller  Error creating: pods "network-problem-detector-host-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].hostPort: Invalid value: 1011: Host port 1011 is not allowed to be used. Allowed ports: [] spec.containers[0].hostPort: Invalid value: 1012: Host port 1012 is not allowed to be used. Allowed ports: []]
```

**What you expected to happen**:
`nwpdcli deploy agent` results in running pods in the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
Kubernetes: v1.21.10

**Comment by MartinWeindel** [comment]
Fixed with commit https://github.com/gardener/network-problem-detector/commit/2ef21b7e1b4089f5c09de1d0cea4ca64aa52c06e
